name: PR Title Check (github-script)

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

permissions:
  pull-requests: read

jobs:
  check:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title || "";
            // 大小写不敏感：^HW(0|[1-9]|1[0-9]|20)\s*-\s*\S.*$
            const re = /^HW(0|[1-9]|1[0-9]|20)\s*-\s*\S.*$/i;
            if (!re.test(title)) {
              core.setFailed(
                `Invalid PR title: "${title}"

Required format:
  HW{#} - {Name}

Where:
  # is an integer from 0 to 20 (inclusive)
    '-' may have spaces around it
    {Name} must contain at least one non-space character

Examples:
  HW0 - Bean
  HW3 - Zoey
  HW20 - Bean

Not allowed:
  HW21 - xxx        (out of range)
  HW3-              (missing name)
  HW03 - xxx        (leading zero)`
  );
  }
